# Form implementation generated from reading ui file 'MainView.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(0, 250))
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 250))
        self.deviceLayout = QtWidgets.QWidget(parent=mainWindow)
        self.deviceLayout.setObjectName("deviceLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.deviceLayout)
        self.horizontalLayout.setObjectName("horizontalLayout")
        mainWindow.setCentralWidget(self.deviceLayout)
        self.menuBar = QtWidgets.QMenuBar(parent=mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        self.loadMenu = QtWidgets.QMenu(parent=self.menuBar)
        self.loadMenu.setObjectName("loadMenu")
        self.uiMenu = QtWidgets.QMenu(parent=self.menuBar)
        self.uiMenu.setObjectName("uiMenu")
        mainWindow.setMenuBar(self.menuBar)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.loadDeviceDatabaseAction = QtGui.QAction(parent=mainWindow)
        self.loadDeviceDatabaseAction.setObjectName("loadDeviceDatabaseAction")
        self.checkDeviceInfosAction = QtGui.QAction(parent=mainWindow)
        self.checkDeviceInfosAction.setObjectName("checkDeviceInfosAction")
        self.checkConnectivityAction = QtGui.QAction(parent=mainWindow)
        self.checkConnectivityAction.setObjectName("checkConnectivityAction")
        self.addViewerAction = QtGui.QAction(parent=mainWindow)
        self.addViewerAction.setObjectName("addViewerAction")
        self.deleteViewerAction = QtGui.QAction(parent=mainWindow)
        self.deleteViewerAction.setObjectName("deleteViewerAction")
        self.loadMenu.addAction(self.loadDeviceDatabaseAction)
        self.loadMenu.addAction(self.checkDeviceInfosAction)
        self.loadMenu.addSeparator()
        self.loadMenu.addAction(self.checkConnectivityAction)
        self.uiMenu.addAction(self.addViewerAction)
        self.uiMenu.addAction(self.deleteViewerAction)
        self.menuBar.addAction(self.loadMenu.menuAction())
        self.menuBar.addAction(self.uiMenu.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.loadMenu.setTitle(_translate("mainWindow", "载入"))
        self.uiMenu.setTitle(_translate("mainWindow", "视图"))
        self.loadDeviceDatabaseAction.setText(_translate("mainWindow", "选择DeviceDB"))
        self.checkDeviceInfosAction.setText(_translate("mainWindow", "设备信息"))
        self.checkConnectivityAction.setText(_translate("mainWindow", "检查连接"))
        self.addViewerAction.setText(_translate("mainWindow", "添加"))
        self.deleteViewerAction.setText(_translate("mainWindow", "删除"))
